// CONFIDENTIAL — Answer Keys for Sireen Credit Game Quiz Grading
// This file is server-side only and never exposed to the client

export const answerKeys: Record<number, string[]> = {
  1: [
    "A financial reputation system",
    "Experian, Equifax, TransUnion",
    "An account listed on your credit report",
    "False",
  ],
  2: [
    "Payment History",
    "How much credit you use vs. what is available",
    "Payment History and Utilization",
    "5",
  ],
  3: [
    "Bank account balances",
    "Reviewing every line carefully",
    "False",
  ],
  4: [
    "On-time payment",
    "It suggests you may be financially over-extended",
    "False",
  ],
  5: [
    "Closing old accounts improves your score",
    "False",
    "False",
  ],
  6: [
    "Perform a credit report audit",
    "Experian, Equifax, TransUnion",
    "Date of First Delinquency",
    "False",
    "True",
    "Yes",
  ],
  7: [
    "Strengthen identity accuracy before disputing accounts",
    "False",
    "Yes",
  ],
  8: [
    "Fair Credit Reporting Act",
    "False",
    "Yes",
  ],
  9: [
    "Fair Debt Collection Practices Act",
    "False",
    "Yes",
  ],
  10: [
    "Date of First Delinquency",
    "False",
    "Yes",
  ],
  11: ["Dispute if inaccurate; goodwill if accurate", "False"],
  12: ["Original creditor, amount, and proof of responsibility", "Yes"],
  13: ["Negotiate a reduced balance for account closure", "Yes", "False"],
  14: ["Method of Verification", "Yes", "Yes"],
  15: ["On-time payments, low utilization, secured cards", "True", "Yes"],
  16: ["Mixed file or identity theft scenario", "Yes", "False"],
  17: ["12", "False"],
  18: ["Audit, Dispute, Escalate, Rebuild", "True"],

  101: [
    "Dun & Bradstreet",
    "PAYDEX",
    "No",
    "Experian",
    "Yes",
  ],
  102: [
    "A supplier offering payment terms",
    "Pay within 30 days",
    "No",
    "Vendor tradelines",
    "Yes",
  ],
  103: [
    "All of the above",
    "Owner promises to repay debt personally",
    "Financial tradelines",
    "Yes",
    "Credit utilization",
  ],
  104: [
    "Uniform Commercial Code",
    "Loan collateral claim",
    "Secretary of State",
    "Tax lien",
    "Yes",
  ],
  105: [
    "A supplier credit account",
    "Payment required within 30 days",
    "5",
    "Paying early",
    "No",
  ],
  106: [
    "PAYDEX",
    "0–100",
    "Likelihood of delinquency",
    "Probability of delinquency",
    "No",
  ],
  107: [
    "Vendor tier",
    "Retail credit",
    "Fleet tier",
    "Cash credit",
    "Payment history",
  ],
  108: [
    "A supplier allowing payment within 30 days",
    "They are easier to obtain",
    "5–8",
    "Report payment activity",
    "Yes",
  ],
  109: [
    "Vendor credit",
    "80",
    "Retail credit",
    "Cash credit",
    "Yes",
  ],
  110: [
    "Yes",
    "Credit reports",
    "Reporting source",
    "It may be removed",
    "Protect financing opportunities",
  ],
  111: [
    "Credit scores",
    "Shows stability",
    "Revenue",
    "High credit utilization",
    "Low risk",
  ],
  112: [
    "Applying for multiple credit accounts strategically",
    "To secure multiple approvals",
    "$50K–$150K",
    "On-time payments",
    "Yes",
  ],
};
